import Footer from '@/components/Footer'
import Header from '@/components/Header'
import Script from 'next/script'

import { Inter } from 'next/font/google'
import ScrollTop from '@/components/ScrollTop'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Clentac - Professional Cleaning Services',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <meta charSet="utf-8"/>
        <meta httpEquiv="x-ua-compatible" content="ie=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="css/bootstrap.min.css"/>
        <link rel="stylesheet" href="css/animate.min.css"/>
        <link rel="stylesheet" href="css/magnific-popup.css"/>
        <link rel="stylesheet" href="css/fontawesome-all.min.css"/>
        <link rel="stylesheet" href="css/odometer.css"/>
        <link rel="stylesheet" href="css/jarallax.css"/>
        <link rel="stylesheet" href="css/swiper-bundle.min.css"/>
        <link rel="stylesheet" href="css/BeerSlider.css"/>
        <link rel="stylesheet" href="css/tg-cursor.css"/>
        <link rel="stylesheet" href="css/slick.css"/>
        <link rel="stylesheet" href="css/default.css"/>
        <link rel="stylesheet" href="css/aos.css"/>
        <link rel="stylesheet" href="css/style.css"/>
        <link rel="stylesheet" href="css/responsive.css"/>        
      </head>
      <body className={inter.className}>
      <Header/>
      <ScrollTop/>
      {children}
      <Footer/>

      <Script type="text/javascript" src="js/vendor/jquery-3.6.0.min.js"/>
      <Script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.3.2/js/bootstrap.min.js"/>
      <Script type="text/javascript" src="js/jquery.magnific-popup.min.js"/>
      <Script type="text/javascript" src="js/jquery.odometer.min.js"/>
      <Script type="text/javascript" src="js/BeerSlider.js"/>
      <Script type="text/javascript" src="js/jquery.appear.js"/>
      <Script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/10.3.1/swiper-bundle.min.js"/>
      <Script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jarallax/2.1.4/jarallax.min.js"/>
      <Script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.8.1/slick.min.js"/>
      <Script type="text/javascript" src="js/gsap.js"/>
      <Script type="text/javascript" src="js/ScrollTrigger.js"/>
      <Script type="text/javascript" src="js/SplitText.js"/>
      <Script type="text/javascript" src="js/gsap-animation.js"/>
      <Script type="text/javascript" src="js/tg-cursor.min.js"/>
      <Script type="text/javascript" src="js/wow.min.js"/>
      <Script type="text/javascript" src="js/aos.js"/>
      <Script type="text/javascript" src="js/main.js"/>
      </body>
    </html>
  )
}
